import { Typography, Divider, Tag } from 'antd'
import { RobotOutlined, LinkOutlined } from '@ant-design/icons'

const { Paragraph, Text } = Typography

interface Props {
  summary: string
  period: string
}

/**
 * Split the executive summary into body text and Foundry IQ citation footnotes.
 * The narrator appends "Sources: Title1 · Title2" when Foundry grounding is active.
 */
function parseSummary(raw: string): { body: string; citations: string[] } {
  const marker = '\n\nSources: '
  const idx = raw.indexOf(marker)
  if (idx === -1) return { body: raw, citations: [] }
  const body = raw.slice(0, idx)
  const citations = raw.slice(idx + marker.length).split(' · ').filter(Boolean)
  return { body, citations }
}

export default function ExecutiveSummary({ summary, period }: Props) {
  const { body, citations } = parseSummary(summary)

  return (
    <div style={{ minHeight: 240 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
        <RobotOutlined style={{ color: '#6366f1' }} />
        <Text type="secondary" style={{ fontSize: 12 }}>
          Generated by Azure OpenAI GPT-4o · Foundry IQ grounding
        </Text>
        <Tag color="purple">{period}</Tag>
        {citations.length > 0 && (
          <Tag color="blue" icon={<LinkOutlined />}>
            {citations.length} source{citations.length > 1 ? 's' : ''}
          </Tag>
        )}
      </div>
      <Divider style={{ margin: '0 0 16px' }} />
      <Paragraph style={{ lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
        {body}
      </Paragraph>
      {citations.length > 0 && (
        <div style={{ marginTop: 16, borderTop: '1px solid #f0f0f0', paddingTop: 12 }}>
          <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 6 }}>
            Grounded sources (Foundry IQ · Azure AI Search)
          </Text>
          {citations.map((c, i) => (
            <Tag key={i} style={{ marginBottom: 4, fontSize: 11 }} color="geekblue">
              {c}
            </Tag>
          ))}
        </div>
      )}
    </div>
  )
}
